### ISSUE TITLE
안녕하세요 한림대학교 빅데 전공 한대현입니다.

### ISSUE THREAD

**Issue by gkseogus** [CaerangManagement/caerang-algorithm-study#19]
혹시 따로 스터디를 같이 진행 할 수 있을까요? 현재 허스 회장직을 임시로 맡고 있습니다!

**Comment by younghoonNa** [comment]
현재 스터디 진행방식이 각자 공부한 코드를 PR을 통해 올리는 방식으로 하고있습니다! 스터디이긴 하지만 개인 공부에 가까운 것 같습니다. 방식이 괜찮으시다면 PR올려주시면 merge 해드리겠습니다! 코드 리뷰는 논의 중에 있으며 코드 리뷰가 진행된다면 개인적으로 연락 드리겠습니다.
