### ISSUE TITLE
동아리 외부학생도 참여 가능할까요?

### ISSUE THREAD

**Issue by scarlet0o0** [CaerangManagement/caerang-algorithm-study#21]
안녕하세요 저는 소융대 학생입니다. 씨애랑 동아리원이 아니어도 참여 가능할까요?

**Comment by younghoonNa** [comment]
학번이랑 성함을 알고 있을까요?

**Comment by younghoonNa** [comment]
안녕하세요 씨애랑 부회장 18학번 나영훈이라고 합니다. 혹시 먼저 학번이나 성함을 알 수 있을까요?

**Comment by scarlet0o0** [comment]
19학번 이선홍이라고 합니다!

**Comment by younghoonNa** [comment]
넵 알겠습니다. 나중에 문제 푸시고 PR 올려주시면 확인해보고 머지해드리겠습니다!

**Comment by scarlet0o0** [comment]
넵 감사합니다!
